name: file_structure_toolkit
description: My personal utility for scanning, exporting to file and comparing file structures.
publish_to: "none"
version: 0.0.1

environment:
  sdk: "^3.5.0-180.3.beta"

dependencies:
  animated_tree_view: ^2.2.0
  catppuccin_flutter: ^1.0.0
  collection: ^1.18.0
  desktop_drop: ^0.4.4
  equatable: ^2.0.5
  fast_immutable_collections: ^10.2.4
  filepicker_windows: ^2.1.3
  fluentui_system_icons: ^1.1.243
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_fancy_tree_view: ^1.6.0
  flutter_hooks: ^0.20.5
  json: ^0.20.2
  path: ^1.9.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
